# Generated by Django 3.0.6 on 2020-05-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chrRaces',
            fields=[
                ('raceID', models.IntegerField(db_column='raceID', primary_key=True, serialize=False)),
                ('raceName', models.CharField(db_column='raceName', max_length=100)),
                ('description', models.CharField(db_column='description', max_length=1000)),
                ('shortDescription', models.CharField(db_column='shortDescription', max_length=500)),
            ],
            options={
                'db_table': 'chrRaces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='eveGraphics',
            fields=[
                ('graphicID', models.IntegerField(db_column='groupID', primary_key=True, serialize=False)),
                ('sofFactionName', models.CharField(db_column='sofFactionName', max_length=100)),
                ('graphicFile', models.CharField(max_length=100)),
                ('sofHullName', models.CharField(max_length=100)),
                ('sofRaceName', models.CharField(max_length=100)),
                ('decription', models.TextField()),
            ],
            options={
                'db_table': 'eveGraphics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='eveIcons',
            fields=[
                ('iconID', models.IntegerField(primary_key=True, serialize=False)),
                ('iconFile', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'eveIcons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='eveSound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'eveSound',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='invCategories',
            fields=[
                ('categoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100)),
                ('published', models.BooleanField()),
            ],
            options={
                'db_table': 'invCategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='invGroups',
            fields=[
                ('groupID', models.IntegerField(db_column='groupID', primary_key=True, serialize=False)),
                ('groupName', models.CharField(max_length=100)),
                ('useBasePrice', models.BooleanField()),
                ('anchored', models.BooleanField()),
                ('anchorable', models.BooleanField()),
                ('fittableNonSingleton', models.BooleanField()),
                ('published', models.BooleanField()),
            ],
            options={
                'db_table': 'invGroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='invMarketGroups',
            fields=[
                ('marketGroupID', models.IntegerField(db_column='marketGroupID', primary_key=True, serialize=False)),
                ('marketGroupName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=3000)),
                ('hasTypes', models.BooleanField()),
            ],
            options={
                'db_table': 'invMarketGroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='invTypeMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(db_column='quantiry')),
            ],
            options={
                'db_table': 'invTypeMaterials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='invTypes',
            fields=[
                ('typeID', models.IntegerField(db_column='typeID', primary_key=True, serialize=False)),
                ('typeName', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('mass', models.FloatField()),
                ('volume', models.FloatField()),
                ('capacity', models.FloatField()),
                ('portionSize', models.IntegerField()),
                ('basePrice', models.DecimalField(decimal_places=4, max_digits=19)),
                ('published', models.BooleanField()),
            ],
            options={
                'db_table': 'invTypes',
                'managed': False,
            },
        ),
    ]
